Feature/피드 작성, 수정, 삭제, 좋아요, 상세조회 api
ShyPolarBear/Server pull request #50
Opened 2023-08-16 13:34 UTC by 0sunset0

## 📌 PR 요약

🌱 작업한 내용
- 피드 작성 api
- 피드 수정 api
- 피드 상세 조회 api
- 피드 좋아요 api
- 피드 삭제 api

🌱 PR 포인트
- BaseEntity의 LocalDateTime을 String으로 변경 (yyyy-MM-dd HH:mm:ss 포맷으로 db에 저장되게 함)
- 내가 작성한 피드 조회, 내가 댓글을 작성한 피드 조회 api의 응답값의 리스트 이름을 content으로 임시 변경! (QueryDsl로 리팩토링 할 때 PageResponse 적용할게요)

2023-08-18 23:52 UTC, wonslee commented
앗 BaseEntity 타입 바뀌었군요 
develop에 머지하시면 최신화해서 다시 푸시할께요! (퀴즈 브랜치)

2023-08-19 01:20 UTC, wonslee requested changes
:warning: 피드 삭제 오류

Feed 엔티티의 comments, feedLikes가 CASCADE 설정되어있지 않아서 에러가 발생합니다
`@OneToMany(..., cascade = CascadeType.ALL)` 로 설정하시는걸 추천드려요!

```
Cannot delete or update a parent row: a foreign key constraint fails (`shy_polar_bear`.`comment`, CONSTRAINT `FKmq57ocw5jrw8rd2lot1g8t0v2` FOREIGN KEY (`feed_id`) REFERENCES `feed` (`feed_id`))
```
```
Cannot delete or update a parent row: a foreign key constraint fails (`shy_polar_bear`.`feed_like`, CONSTRAINT `FKgurobtyio3jh1vn4n8tmqt842` FOREIGN KEY (`feed_id`) REFERENCES `feed` (`feed_id`))
```
<br>
<br>
<br>


:question:  FeedImages에는 `@OneToMany` 가 아닌 `@ElementCollection` 을 사용하셨는데 이유가 뭔가요? 자동적으로 CASCADE ALL 적용이 된다고 해서 신기하네요
클래스도 String..!
나중에 Feed쪽에서 FeedImages를 가져올 때 엔티티로써 가져올 수 있는건가요?
<br>


:heavy_check_mark: 생성, 수정 API 정상작동 확인했습니다

2023-08-19 01:20 UTC, wonslee commented on src/main/java/com/shy_polarbear/server/domain/feed/dto/request/CreateFeedRequest.java
> +    private List<String> feedImages;
validate 사용하시면 더 좋을거같아요!
보통 title과 content같은 문자열은 `@NotNull` 혹은 `@NotBlank`를 써서 유효성 검사를 해요

2023-08-19 01:20 UTC, wonslee commented on src/main/java/com/shy_polarbear/server/global/common/model/BaseEntity.java
> +    }
:heavy_check_mark:  확인했습니다

2023-08-19 01:20 UTC, wonslee commented on src/main/java/com/shy_polarbear/server/global/common/model/BaseEntity.java
> +    @Column(updatable = false)
좋은 속성 알아갑니다!

2023-08-19 02:55 UTC, 0sunset0 commented on src/main/java/com/shy_polarbear/server/domain/feed/dto/request/CreateFeedRequest.java
> +    private List<String> feedImages;
지금까지 제 코드 dto validate 하겠습니다!!

2023-08-19 02:57 UTC, 0sunset0 commented
그게 빨리 머지되는게 좋으니까 삭제/좋아요는 아직 작업을 안했었는데, 그거까지 해서 이 PR로 같이 머지하겠습니다~

2023-08-19 03:30 UTC, 0sunset0 commented
값타입 컬렉션은 모든 칼럼을 묶어서 PK로 쓰는데요!
FeedImages는 이미지 링크(문자열)만 있으면 되니까 이런 단점도 의미가 없지 않을까? 싶어서 값타입 컬렉션으로 가져갔었어요. (사용을 추천하진 않지만 간단한거엔 써도 된다길래)

근데 찾아보니까 값타입 컬렉션은 선수가 출전한 경기의 종목 리스트(축구, 배구, 농구) 같은 추적이 필요 없는 것들만 사용해야 한다고 합니다.. 이미지링크는 값인지 엔티티인지 살짝 헷갈리네요
만약 피드 이미지 링크가 엔티티라면, 유저의 프로필 이미지 링크도 엔티티로 만들어야 하지 않나 하는 의문이 듭니다..

2023-08-19 03:31 UTC, 0sunset0 commented
피드 이미지를 엔티티로 만들고, 피드랑 피드 이미지는 일대다 관계로 바꾸겠습니다!

2023-08-19 08:20 UTC, wonslee commented
아하 그렇군요!
좋은 기능 알아갑니다ㅎㅎ

2023-08-19 08:21 UTC, wonslee approved these changes
:heavy_check_mark: 새로 push 하신 커밋들까지 잘 봤습니다
 정상작동 확인했습니다!

2023-08-19 10:03 UTC, 0sunset0 commented on src/main/java/com/shy_polarbear/server/domain/feed/model/Feed.java
> +    }
피드 안에 isLike() 메서드가 
api 사용자가 피드에게 좋아요 눌렀는지 물어보고, 피드가 피드좋아요에서 존재하는지 물어본다고 생각해서
되게 객체지향적인 코드라고 생각했는데,,,,

지연로딩으로 인해 n+1 문제가 발생하고, 좋아요 취소할 때 이 메서드가 쓰이면 코드 양이 추가되는 단점이 있네요.
제가 DDD 책을 좋게 읽어서 그런지 이런 객체지향적인 코드에 집착하는걸까요...ㅋㅋㅋ

결론은 "성능+간결한 코드"vs "객체지향적인 코드"(나중에 성능 최적화 가능할 수도..) 
이 둘 중에 뭐가 더 낫다고 생각하시는지 궁금합니다!!

2023-08-19 10:54 UTC, wonslee commented on src/main/java/com/shy_polarbear/server/domain/feed/model/Feed.java
> +    }
1문단 : 이 코드는 객체지향적으로 좋은 코드라고 생각. 완전 찬성

2문단 : N+1 문제는 이 메서드 문제라기보단 spring data jpa의 문제예요! 
FETCH JOIN 혹은 default_batch_size 를 참고해보시면 좋을듯 합니다
Feed 쿼리를 칠 때 FeedLike까지 FETCH JOIN을 하면 추가 쿼리가 발생하지 않아요

+`feedLike.isUser` -> `feedLike.getUser.getId.equals(user.getId())` 식으로 하시면 아마 FeedLike-User에 대한 N+1 쿼리 발생은 없어질거예요. Hibernate에서는 FK id값은 기본으로 들고댕기거든요


좋아요 취소는 제가 코드를 못 봐서 모르겠지만 코드가 오히려 깔끔해질거같은데유?

3문단 : 정상 작동 > 성능 >= 객체지향 > 클린코드(이건 완전 제 개인적인 생각.. )

길게 글 쓰려다가 저도 생각정리가 안 돼서 포기했읍니다 :disappointed: 
성능 vs 객체지향 이거 너무 어려운거 아닙니까

2023-08-19 10:57 UTC, wonslee commented on src/main/java/com/shy_polarbear/server/domain/feed/model/Feed.java
> +    }
음.. 누군가가 코드를 하늘에서 내려준다고 한다면..
전 성능 좋은 코드를 선택할거같아요 객체지향으로 리팩토링하는게 더 빠른거같아서ㅋㅋㅋ

2023-08-19 11:07 UTC, wonslee commented
:heavy_check_mark: 좋아요 api 확인했습니다

2023-08-19 11:14 UTC, wonslee commented on src/main/java/com/shy_polarbear/server/domain/feed/model/Feed.java
> +    }
아 `feedLike.isUser` 그렇게 해두셨네요ㅋㅋ sorry.

2023-08-19 11:33 UTC, 0sunset0 commented on src/main/java/com/shy_polarbear/server/domain/feed/model/Feed.java
> +    }
정리를 너무 잘해주셨네요 ㅎㅎㅎ!!!!! 
feedLikeResppsotory로 exist 쿼리를 날리면 feedLike에서 바로 찾지만,
feed의 isLike()를 호출하게 되면, feed의 feedLike를 하나씩 가져온 다음 찾기 때문에 쿼리 개수가 많아지는거 같아요(fetch join 안했다고 가정했을 때)

추가로 좋아요에서는 확실하진 않은데  feed의 feedLikes를 가져와서 그런건지.. 동기화 문제 때문에 delete 쿼리가 안나가더라구요 
<좋아요에서 isLike() 사용>
```java
    public LikeFeedResponse switchFeedLike(Long feedId) {
        User user = userService.getCurruentUser();
        Feed feed = findFeedById(feedId);
        if (!feed.isLike(user)) {
            FeedLike feedLike = FeedLike.createFeedLike(feed, user);
            feedLikeRepository.save(feedLike);
            return new LikeFeedResponse("좋아요 처리되었습니다.");
        } else {
            feed.getFeedLikes().removeIf(feedLike -> feedLike.isUser(user)); //이 코드 추가
            feedLikeRepository.deleteByUserAndFeed(user, feed);
            return new LikeFeedResponse("좋아요 취소되었습니다.");
        }
    }
```

<좋아요에서 feedLikeResppsotory 사용> 
```java
    public LikeFeedResponse switchFeedLike(Long feedId) {
        User user = userService.getCurruentUser();
        Feed feed = findFeedById(feedId);
        if (!feedLikeRepository.existsByUserAndFeed(user, feed)) {
            FeedLike feedLike = FeedLike.createFeedLike(feed, user);
            feedLikeRepository.save(feedLike);
            return new LikeFeedResponse("좋아요 처리되었습니다.");
        } else {
            feedLikeRepository.deleteByUserAndFeed(user, feed);
            return new LikeFeedResponse("좋아요 취소되었습니다.");
        }
    }
```

2023-08-19 11:33 UTC, 0sunset0 commented on src/main/java/com/shy_polarbear/server/domain/feed/model/Feed.java
> +    }
코멘트를 이렇게 길게 달아도 되나요 먼가 지엽적인 느낌..ㅎㅎ

2023-08-19 11:54 UTC, 0sunset0 commented on src/main/java/com/shy_polarbear/server/domain/feed/model/Feed.java
> +    }
일단 이대로 머지하고 나중에 성능최적화를 고려해보겠습니다...
(좋아요에서는 feedLikeRepository.existsByUserAndFeed() 사용할게요)

2023-08-19 12:40 UTC, merged

2023-08-20 04:54 UTC, wonslee commented on src/main/java/com/shy_polarbear/server/domain/feed/model/Feed.java
> +    }
:+1: 확인했습니다!

delete 말씀하신 부분은 사실 나가는 쿼리가 똑같아서 지금 버전이 더 좋은거같아요
넵 성능최적화는 리팩토링때 하는게 편하죠ㅎㅎ