테스트코드 작성, 리팩토링
ShyPolarBear/Server pull request #57
Opened 2023-08-26 07:20 UTC by 0sunset0

## 📌 PR 요약

🌱 **작업한 내용**
- user, feed 엔티티 칼럼 제약조건 설정 (nullable, 기본값 설정, 유니크 제약 조건)
- 피드 작성 수정 시 이미지를 주지 않아도 되게 변경 (bug fix..) 
- @AuthenticationPrincipal로 User를 컨트롤러에서 찾아오게 변경
- User의 provider를 enum으로 변경 
- User, Feed 테스트 코드 작성

🌱 **PR 포인트**
- 테스트 코드는 @SpringBootTest로 mock 객체 사용 안했습니다.
- FeedServiceTest에서 updateFeed() 메서드 테스트 실패합니다 ㅠㅠ (포스트맨으로 요청하면 잘되는데 왜 테스트 실패하는지 도저히 모르겠어요.. 테스트 하나에 시간을 많이 쓸 수 없어서 원석님 보시면 코드 주석 지우고 merge하겠습니다!)
```java
    public void update(String title, String content, List<FeedImage> feedImages) {
        this.title = title;
        this.content = content;
        this.feedImages.clear(); //UnsupportedOperationException 발생
        if (feedImages != null) {
            assignFeedToFeedImages(feedImages, this);
            this.feedImages.addAll(feedImages);
        }
    }
```
feed 엔티티 안에 있는 update() 메서드에서, feedImages.clear()할 때 
UnsupportedOperationException이 발생합니다..😱

|테스트 실행 결과|
|:--:|
|![image](https://github.com/ShyPolarBear/Server/assets/81086966/0ac3a869-c968-4488-bd5d-f74163110fbe)|

## 📮 관련 이슈
- Resolved: #54

2023-08-26 07:25 UTC, jinukeu reviewed
PR 요약의 테스트 부분만 봐도 엄청난게 느껴지네요!
고생하셨습니다~!! 💯

2023-08-26 07:25 UTC, jinukeu commented on src/main/java/com/shy_polarbear/server/domain/feed/dto/request/UpdateFeedRequest.java
> +    @Size(max = 5)
max = 5, BusinessLogicConstants.java에서 관리하는건 어떠세요?
최대 이미지 수의 경우 기획상 변동이 발생할 수 있는데, CreateFeedRequest, UpdateFeedRequest 2곳에서 사용되더라구요!?

실수로 한 곳의 max 값만 수정할 가능성이 있으니 Constants에서 관리하는게 더 좋아보입니다.

2023-08-26 07:59 UTC, 0sunset0 commented on src/main/java/com/shy_polarbear/server/domain/feed/dto/request/UpdateFeedRequest.java
> +    @Size(max = 5)
수정했습니다~ 원석님인 줄 알았는데 PM분한테 리뷰도 받고 좋네요 ㅎㅎ 감사해요

2023-08-26 08:39 UTC, wonslee requested changes
에러 2개 발견했어유!
엔티티 수정, Initializer 수정 사항까지만 봤습니다

2023-08-26 08:39 UTC, wonslee commented on src/main/java/com/shy_polarbear/server/global/common/dummy/FeedInitializer.java
> +        User user = userRepository.findByProviderId("0")
:red_circle: 해당 값은 LoginUserInitializer의 상수값과 달라서 에러가 발생합니다!


![image](https://github.com/ShyPolarBear/Server/assets/72124326/6d6ccd35-c3b4-4c6a-bae8-197d614ecdce)

추천드리는 해결 방법
- `findFirst...` , `findAll...`로 특정 값을 넣지 않고 조회하기
- providerId를 글로벌 상수화하기 (public 접근자)

2023-08-26 08:39 UTC, wonslee commented on src/main/java/com/shy_polarbear/server/domain/user/model/User.java
> +@Table(uniqueConstraints = {@UniqueConstraint(name = "user_unique", columnNames = {"nickName", "providerId", "provider", "password"})})
UNIQUE 제약을 여러컬럼에 묶어 적용하는건 처음 보네요 역시 꼼꼼하시군요...!

2023-08-26 08:39 UTC, wonslee commented on src/main/java/com/shy_polarbear/server/domain/user/model/User.java
> +@Table(uniqueConstraints = {@UniqueConstraint(name = "user_unique", columnNames = {"nickName", "providerId", "provider", "password"})})
:red_circle: DDL 에서 유니크 키가 생성되는데, 이 길이가 너무 길다고 하네요

```
Caused by: java.sql.SQLSyntaxErrorException: Specified key was too long; max key length is 3072 bytes
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:121) ~[mysql-connector-j-8.0.33.jar:8.0.33]
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122) ~[mysql-connector-j-8.0.33.jar:8.0.33]
	at com.mysql.cj.jdbc.StatementImpl.executeInternal(StatementImpl.java:763) ~[mysql-connector-j-8.0.33.jar:8.0.33]
Caused by: java.sql.SQLSyntaxErrorException: Specified key was too long; max key length is 3072 bytes
```

서버 작동에는 문제 없지만 DB에 유니크 키가 생성되지 않고 있네요..!
![image](https://github.com/ShyPolarBear/Server/assets/72124326/942adbec-e693-4a84-af84-9f84e33fd060)


[찾아보니](https://hackmd.io/@bonjugi/SkslMXSaE) String 필드는 디폴트로 varchar 255로 설정 -> 255 * 4 byte ([utf8 확장 + 이모지](https://cirius.tistory.com/1769)) = 1020 byte
1020 * 컬럼 개수 4 = 4080 > 3072 => 에러
시험삼아 provider을 빼봤는데 잘 되네요

2023-08-26 08:39 UTC, wonslee commented on src/main/java/com/shy_polarbear/server/domain/user/model/User.java
> +@Table(uniqueConstraints = {@UniqueConstraint(name = "user_unique", columnNames = {"nickName", "providerId", "provider", "password"})})
단일 유니크 필드로써 nickName, providerId을 따로 설정하는건 어떻게 생각하세요?
 `@Column(unique = true)` 식으루요

묶게 되면 아마 nickName이 중복되어도 다른 필드가 다르면 DB에선 그냥 넘길거예요

제가 유저 테이블에 대한 파악이 아직 덜 돼서 ,, 노을님 조언이 필요합니다!

2023-08-26 09:23 UTC, 0sunset0 commented on src/main/java/com/shy_polarbear/server/global/common/dummy/FeedInitializer.java
> +        User user = userRepository.findByProviderId("0")
그렇네요,,, 제가 로그를 정말 꼼꼼히 안보는걸 깨달았습니다 추천해주신 해결 방법으로 수정하겠습니다!!

2023-08-26 09:39 UTC, 0sunset0 commented on src/main/java/com/shy_polarbear/server/domain/user/model/User.java
> +@Table(uniqueConstraints = {@UniqueConstraint(name = "user_unique", columnNames = {"nickName", "providerId", "provider", "password"})})
음 제가 @Table로 한 이유는 유니크키 이름을 지정할 수 있어서였는데요!
@Column으로 하면 각각의 유니크키가 생성되고 alter 쿼리도 키 개수만큼 나가게 됩니다 
유니크키 이름도 `UK_redywmoh8x2ku6ab3ghhkk2nr` 이런식으로 이해할 수 없는 문자열로 자동생성되구요... 만약 칼럼의 나중에 중복을 허용한다면, 단순히 
 @Column(unique = false) 이렇게 바꿔줘도 유니크 제약조건이 풀리지 않아요. 유니크키를 찾아서 제거 해줘야 합니다! (그래서 유니크 키 이름이 직관적인게 좋다고 생각했었어요)
 
근데 원석님이 말씀하신 것 처럼 nickName, providerId 둘 다 유니크 해야하고
부끄북극 기획 상 nickName과 providerId가 중복을 허용할 경우는 없기 때문에 @Column 으로 제약조건 걸겠습니다~!

2023-08-27 04:41 UTC, wonslee commented on src/main/java/com/shy_polarbear/server/global/common/constants/BusinessLogicConstants.java
> +public abstract class BusinessLogicConstants {
오오 인스턴스화 방지하는 목적인가요?
개선해주셔서 감사합니다 :+1:

2023-08-28 12:19 UTC, wonslee approved these changes
:white_check_mark: 확인했습니다!

2023-08-28 12:19 UTC, wonslee commented on src/test/java/com/shy_polarbear/server/domain/feed/service/FeedServiceTest.java
> +                        (ExceptionStatus.NOT_FOUND_FEED).getClass(),
저도 공부해봤는데, 이거 `FeedException.class` 와 값이 같네요!
assertThrows에선 큰 틀의 에러 클래스밖에 못 잡나봐요

구체적인 ExceptionStatus까지 잡으려면 Controller을 테스트해야 할 것 같아요

2023-08-28 12:19 UTC, wonslee commented on src/test/java/com/shy_polarbear/server/domain/feed/service/FeedServiceTest.java
> +//    }
updateFeed의 getFeedImages 결과값의 클래스가 이렇게 나오는데... 이거랑 관련 있는지 모르겠네요
레퍼런스도 잘 안나오구요..
저도 해결을 못해서 뭐라고 드릴 말씀이... :disappointed: 

![image](https://github.com/ShyPolarBear/Server/assets/72124326/14639184-4477-40fe-a102-447ee1715d76)

2023-08-28 13:25 UTC, 0sunset0 commented on src/test/java/com/shy_polarbear/server/domain/feed/service/FeedServiceTest.java
> +                        (ExceptionStatus.NOT_FOUND_FEED).getClass(),
갑자기 예외 메세지를 비교해서 테스트코드를 작성하는 경우가 생각나서
```java
    @DisplayName("findFeed()메서드는 피드가 존재하지 않는다면 FeedException을 던진다.")
    @Test
    void findFeed_exception() {
        FeedException feedException = assertThrows(FeedException.class, () -> feedService.findFeed(-1L, user));
        assertThat(feedException.getExceptionStatus()).isEqualTo(ExceptionStatus.NOT_FOUND_FEED);
    }
```

이런식으로 ExceptionStatus도 비교하게 변경했습니다~ 

그리고 이전 코드에서 `getClass()` 결국 예외 클래스 타입를을 비교하고 있는데 제가 왜 굳이 파라미터를 넘기면서 객체를 만들었는지 모르겠네요... (아마 생각 없이 코드를 가져와서 그런거 같네요) 그래서 `FeedException.class` 이걸로 수정했습니다!!!

2023-08-28 13:29 UTC, 0sunset0 commented on src/test/java/com/shy_polarbear/server/domain/feed/service/FeedServiceTest.java
> +//    }
원석님... 진짜 감사합니다!!!!

제가 피드이미지를 List<String>에서 List<FeedImage>로 변경하는 메서드를 이렇게 만들었었어요
```java
    public static List<FeedImage> createFeedImages(List<String> urls) {
        return urls.stream()
                .map(url -> new FeedImage(url))
                .toList(); //주목!!
    }
```

근데 toList() 메서드를 커멘드 B 로 들어가서 보면
![image](https://github.com/ShyPolarBear/Server/assets/81086966/75d8cfbf-74a4-41f1-85ac-f80796f1e01e)
unmodifiableList()라는 메서드는

2023-08-28 13:31 UTC, 0sunset0 commented on src/test/java/com/shy_polarbear/server/domain/feed/service/FeedServiceTest.java
> +//    }
원석님... 진짜 감사합니다!!!!

제가 피드이미지를 List<String>에서 List<FeedImage>로 변경하는 메서드를 이렇게 만들었었어요
```java
    public static List<FeedImage> createFeedImages(List<String> urls) {
        return urls.stream()
                .map(url -> new FeedImage(url))
                .toList(); //주목!!
    }
```

근데 toList() 메서드를 커멘드 B 로 들어가서 보면
![image](https://github.com/ShyPolarBear/Server/assets/81086966/75d8cfbf-74a4-41f1-85ac-f80796f1e01e)
unmodifiableList()라는 메서드는 불변리스트를 반환하고 있어요
![image](https://github.com/ShyPolarBear/Server/assets/81086966/4b0cb9d2-c2b8-444a-83f6-97f5fd3ed0b7)
그래서 Feed 객체를 생성할 때 불변리스트로 피드이미지 리스트가 초기화되고,  수정 시 clear()라는 메서드 지원되지 않는거였어요!!

2023-08-28 13:38 UTC, 0sunset0 commented on src/test/java/com/shy_polarbear/server/domain/feed/service/FeedServiceTest.java
> +//    }
Arrays.asList가 아니라 new ArrayList()로 리스트가 만들어져서 
 왜 UnsupportedOperationException가 발생하는지 몰랐는데
그걸 한번 더 감싸서 불변리스트(ListN)로 만들어져서였어요~! ListN은 clear() 메서드를 오버라이드하고 있지 않아 UnsupportedOperationException 이였네요..ㅎㅎㅎ

2023-08-28 13:39 UTC, 0sunset0 commented on src/test/java/com/shy_polarbear/server/domain/feed/service/FeedServiceTest.java
> +//    }
포스트맨으로는 분명 이미지 3개->2개로 수정이 되었는데 
왜 됐는지는 모르겠네요

2023-08-29 03:23 UTC, wonslee commented on src/test/java/com/shy_polarbear/server/domain/feed/service/FeedServiceTest.java
> +                        (ExceptionStatus.NOT_FOUND_FEED).getClass(),
오오 assertThrow 반환값이 있었군요

요 코드는 어떠세요? 복쟉복쟉 킹백엔드마스터우영두씨가 작성했습니다.
https://github.com/Akatsuki-USW/Buzzzzing-Server/blob/develop/src/test/java/bokjak/bokjakserver/domain/user/service/UserServiceTest.java

2023-08-29 04:09 UTC, wonslee commented on src/test/java/com/shy_polarbear/server/domain/feed/service/FeedServiceTest.java
> +//    }
아하~~~~ 이해했어요!
오 근데 기존에 피드 업데이트가 됐던게 신기하네요

JPA에서 DB에 INSERT 쿼리 나가는 순간 Immutable Collection은 그냥 리스트가 되나보네요 
테스트상에 있던 Feed는 영속성 컨텍스트상에 있어서 그런건가 싶네요

🚀

2023-08-29 07:44 UTC, 0sunset0 commented on src/test/java/com/shy_polarbear/server/domain/feed/service/FeedServiceTest.java
> +//    }
![image](https://github.com/ShyPolarBear/Server/assets/81086966/6ceeaac6-ff34-4603-9ba7-5004bf72cd50)
PersistentBag으로 래핑해서 사용한다고 하네요..! 하이버네이트는 PersistentBag를 인스턴스를 이용하여 영속성 전이와 고아객체  추적해서 
orphanRemoval 옵션 사용시 Collection 참조를 변경하면 안된다고 하네요..! (원래 ArrayList를 비우고 다시 채워넣어야 하는 이유)

2023-08-29 07:54 UTC, 0sunset0 commented on src/test/java/com/shy_polarbear/server/domain/feed/service/FeedServiceTest.java
> +                        (ExceptionStatus.NOT_FOUND_FEED).getClass(),
ㅋㅋㅋㅋㅋㅋㅋㅋ메서드 체이닝 너무 좋습니다! 
저도 assertThatThrownBy()로 수정했습니다 감사해요

2023-08-29 11:06 UTC, wonslee commented on src/test/java/com/shy_polarbear/server/domain/feed/service/FeedServiceTest.java
> +//    }
오호 덕분에 지식이 늘었어요 공부할게 많네요..! :rocket:

2023-08-29 11:12 UTC, merged